### ISSUE TITLE
Ticket open fails

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk-android-app#11]
In the inbox page, as soon as i open the ticket, app crashes

**Comment by sumitl920** [comment]
Have already mentioned this in issue#8

⚫App was crashing for ticketID 1563 because body is HTML text and has % in height:100%. This breaks string formatting in Java.

It will crash for every ticket which has similar conversation thread. Don't send html content and it will fix automatically

**Comment by bhanu2217** [comment]
@sujit223 @vijaysebastian  Can you look into it and work on a solution with Sumit

**Comment by bhanu2217** [comment]
Most of the tickets this problem is happening & app crashes, Sumit please discuss with Vijay & Sujit what is the best solution on this matter

**Comment by bhanu2217** [comment]
We allow HTML tags in our tickets/mails

**Comment by bhanu2217** [comment]
There are so many email apps in android market place which display HTML tags and HTML emails. How are they doing it? 
HTML emails is an important feature of our app we cannot disable HTML emails.
If you want certain,specific HTML tags to be disabled we can do that but again it shouldn't break the design of our HTML emails

**Comment by sumitl920** [comment]
Well I don't deny it cannot be done. It's just not straight forward.
Example, for our app I had put textView to handle texts which come in in replies. To handle basic html tags, a little modification is needed, which again, can be done, because android textViews support basic tags.
But to support all the html contents modifications are needed which is not straight forward.

Email apps are built specifically for that. To handle html contents.

**Comment by sumitl920** [comment]
Tags like for paragraphs, italics will be handle by TextView after little modification.

But something like width:100% will never be handled by TextView because they are android elements with their own widths. We have to put WebView to handle it, which takes time to tweak to our needs in this case.

**Comment by bhanu2217** [comment]
HTML tags are not set by us. These are the emails that we get from our clients and we have no control over the html used in these emails.
We should probably use Web View as suggested by you. Our app is more or less acting like an email client/reader

**Comment by sumitl920** [comment]
Fixed
