### ISSUE TITLE
Company URL Page

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk-android-app#12]
- No proper error message for invalid url structure
- No proper error message incase the url is not of valid Faveo Helpdesk, i mean if the API fails

**Comment by sumitl920** [comment]
Have already mentioned this in issue#8

⚫App was crashing for ticketID 1563 because body is HTML text and has % in height:100%. This breaks string formatting in Java.

It will crash for every ticket which has similar conversation thread. Don't send html content and it will fix automatically.

**Comment by sumitl920** [comment]
I need respective text from backend to show it.

**Comment by bhanu2217** [comment]
@sumitl920 
No:1 is just basic url validation, in case someone puts url without http or https or which is not a valid url. This has not link to API.

No:2 Here the API will not work at all. As the url which is entered by user doesn't hit the API, it's not a valid Faveo installation url. So this message is again something you display, it has not dependancy on API

**Comment by sumitl920** [comment]
Normal valid url is okay to check.
How would I know if it is a valid faveo helpdesk url? Does it start with something specific?
Eg. I can check for faveohelpdesk.com/ validity. But if user fills abc after that, how would I know if that is valid url?

**Comment by sumitl920** [comment]
Also, there are 2 urls that I know of. 
faveohelpdesk.com and ladybirdweb.com
Is there anymore url? I can do a hardcoded check. But then again if you change to a diff url or add one more url, these checks would fail.

**Comment by bhanu2217** [comment]
URL will keep changing, this is not fixed element, different client will use different urls. URL is where client has installed Faveo online. This is not something we can control or know off

**Comment by bhanu2217** [comment]
Regarding how to check if URL is valid Faveo url, when you send the request and lets say within 30second you don't get any response then its probably wrong url

**Comment by sumitl920** [comment]
Fixed
