### ISSUE TITLE
Ticket List page does not display Client name.

### ISSUE THREAD

**Issue by sujit223** [ladybirdweb/faveo-helpdesk-android-app#19]
For some reason in the ticket list page the name of the ticket owner is not displayed only in case of tickets raised by client. But tickets raised by agents will display name of the ticket owner.

**Comment by sumitl920** [comment]
Can you give me the ticketID?

**Comment by sujit223** [comment]
Almost all the tickets in the inbox page. But there is a slight possibility that tickets generated in the demo link are mostly created by agents. Try to create a ticket without logging into the system and then try to view that ticket.

**Comment by sujit223** [comment]
If you are testing in faveohelpdesk.com/demo then in the inbox list page Ticket number AAIR-0255-0000255 is a ticket I just created please have a check. The name of the agent is not displayed.

**Comment by sumitl920** [comment]
Think this was related to issue #8. Does this work now?
