### ISSUE TITLE
Creating ticket issue

### ISSUE THREAD

**Issue by sujit223** [ladybirdweb/faveo-helpdesk-android-app#20]
These issue relates to create ticket page:-
- Helptopic seems to be hardcoded. There are 3 helptopic in the system but seems only two in app.
- SLA seems to be hardcoded. There are 3 sla 6,12,24 in the system but in app they are 6,12,18.
- Assign to seems to be hardcoded. there are atleast 10 agents but only displays 4.
- Please do check Priority too seems doubtful.

**Comment by sumitl920** [comment]
These were already mentioned by Bhanu in issue #8
