### ISSUE TITLE
Ticket detail page issue

### ISSUE THREAD

**Issue by sujit223** [ladybirdweb/faveo-helpdesk-android-app#21]
These issue relates to ticket detail page:-
- Display profile pic in the conversation list page.
- Instead of client, support and internal note please display name of the conversations. in case of internal note some times it could be the agent or admin in the internal.
- In detail page sla plan seems hardcoded. System has different hours.
- Display department name not id
- Helptopic is hardcoded it should be dynamic.
- Name should display name not id
- Email should display email but not available
- source should display source names but not source id
- Assign to seems hardcoded. It should be dynamic.

**Comment by sumitl920** [comment]
These were already mentioned by Bhanu in issue #8
