### ISSUE TITLE
Client list page

### ISSUE THREAD

**Issue by sujit223** [ladybirdweb/faveo-helpdesk-android-app#22]
Some bugs with this link doesnot load client list page:-
faveohelpdesk.com/demo

But it loads for ladybirdweb.com/support
but with some UI related issue
1. Client gravatar is not displayed
2. Client ticket list is not displayed under client panel
3. Cant test any more on here the app stopped working even after fresh installation.

**Comment by sumitl920** [comment]
These were already mentioned by Bhanu in issue #8
