### ISSUE TITLE
Ticket details - Release 7

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk-android-app#26]
- Most of the things in this page are not working or hard coded probably
- Save button also not working
- No option give to see whom the tickets are assigned too
- Due date not showing
- Last Message is the name of the person/agent who replied last
- Name and email of the person who created ticket not showing
- Status is showing twice

**Comment by bhanu2217** [comment]
On the detail page, what is shown shown as subject is the first message and not subject. 
There is also subject above it which is centre aligned. So we can just keep one subject

**Comment by pajames110** [comment]
Resolved issues:
Save button is properly working and saving data.
Status is showing once.
