### ISSUE TITLE
My ticket doesnot work for me

### ISSUE THREAD

**Issue by sujit223** [ladybirdweb/faveo-helpdesk-android-app#37]
All tickets loaded message. But no tickets in display. There are around 10 tickets under my tickets under me.

**Comment by sumitl920** [comment]
Could you check this in demo and let me know? Clear app data and check once.

**Comment by sujit223** [comment]
Only those tickets load that are replied or performed any action on any of the tickets that are assigned to me in mytickets but those tickets dont load that are not performed any action but assigned to me which are suppose to be showing under my tickets

**Comment by pajames110** [comment]
Issue resolved in the updated version. All the tickets with the proper replies can be seen.
