### ISSUE TITLE
Doesnt work with 1.0.7.5 version

### ISSUE THREAD

**Issue by supportreq** [ladybirdweb/faveo-helpdesk-android-app#50]
It seems the android app is stuck at the login screen while using with 1.0.7.5 version..

please advice..

**Comment by bhanu2217** [comment]
@SarfrazS and @baratam-narendra  Can you please test this

**Comment by narendra-baratam** [comment]
yes sir

**Comment by jhajhaja** [comment]
Because its sdk version is very less

**Comment by bhanu2217** [comment]
@jhajhaja Didn't get you?

**Comment by jhajhaja** [comment]
I mean to say that its sdk version where the app executes is 1.0 but while
developing the min sdk version was 2.0

**Comment by narendra-baratam** [comment]
minSdkVersion 14
 targetSdkVersion 23
 compileSdkVersion 23

The app will works from API level 14 to API level 23, in that means it have compatibility from iceCream-Sandwich(4.0.1) to Marshmallow (6.0)

**Comment by supportreq** [comment]
@baratam-narendra @jhajhaja so does the app work with v1.0.7.5 of your faveo-helpdesk

**Comment by supportreq** [comment]
any update for this? it seems that the app is unable to understand the json reply once connected.. returns null.. can you confirm @bhanu2217

**Comment by bhanu2217** [comment]
Haven't tested this version on mobile app. We will test it Monday and then provide a fix if required.

**Comment by bhanu2217** [comment]
We have figured out the issue,a route link for one particular api went missing. We will provide fix in next release.

**Comment by supportreq** [comment]
@bhanu2217 when is the next release??

**Comment by bhanu2217** [comment]
Sometime today

Sent from Yahoo Mail on Android 

  On Tue, Jun 21, 2016 at 8:49 AM, supportreqnotifications@github.com wrote:  
@bhanu2217 when is the next release??

**Comment by supportreq** [comment]
@bhanu2217 any update?

**Comment by bhanu2217** [comment]
App is working now.
We will also be releasing new version of mobile Android app this week.

**Comment by supportreq** [comment]
@bhanu2217 app is working now.. but after an hour i tried to open the app again gives something went wrong error and breaks!

Also please check no push notifications for any new ticket..

**Comment by bhanu2217** [comment]
There are still few issues in the app, we are working on it, we will release new version with bug fixes very soon on Google play store.
Thank You.

**Comment by bhanu2217** [comment]
Push notification will not be part of community edition but pro edition. We have not yet released Pro edition app yet. We are working on Pro edition app also.
