### ISSUE TITLE
Android App not working

### ISSUE THREAD

**Issue by francesco1119** [ladybirdweb/faveo-helpdesk-android-app#51]
I have download the app and installed it on Samsung Galaxy S3 but as I enter the URL http://faveo.jeeja.biz nothing happens.

**Comment by kreatorcodes** [comment]
@baratam-narendra and @vijaysebastian  can you check why is it not working?

**Comment by SarfrazS** [comment]
Hi Franceseco1119,

Please Use full URL http://faveo.jeeja.biz/public

Thank you

**Comment by francesco1119** [comment]
it worked

**Comment by kreatorcodes** [comment]
closing the issue as app is working with the full URL of the system.
