### ISSUE TITLE
User Manual

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk-android-app#52]
Please create a User manual for Both Community edition and Pro edition mobile app and hand it over @SarfrazS urgently for testing

**Community edition user manual:** https://docs.google.com/document/d/1zCK7EWMvxGTi2K2p16Mc9rBl5oNLLH578KVpdQG958c/edit?usp=sharing
**Pro edition user manual:** https://docs.google.com/document/d/16WDxTyghLxPEXxWv47Chmf1VOIkTXmmvuOGKfO9waBc/edit?usp=sharing

**Comment by javerba** [comment]
Hey, do you still need help with your user manuals? I'm a writer (not programmer) looking for a project to work on.

**Comment by bhanu2217** [comment]
Yes we need help on User Manual. Can you email us on support@ladybirdweb.com so we can discuss further.
