### ISSUE TITLE
API issue

### ISSUE THREAD

**Issue by narendra-baratam** [ladybirdweb/faveo-helpdesk-android-app#54]
**URL** http://ladybirdweb.com/support/

In this above URL, the data(Last response date,created date,due date,source,web,..etc) is not coming as it required.

**ERROR** In API:

"error":"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'last_message_at' in 'field list' (SQL: select `tickets`.`dept_id`, `users`.`email`, `users`.`user_name`, `users`.`first_name`, `users`.`last_name`, `tickets`.`id`, `ticket_number`, `user_id`, `priority_id`, `sla`, `status`, `lock_by`, `lock_at`, `source`, `isoverdue`, `reopened`, `isanswered`, `is_deleted`, `closed`, `reopened_at`, `duedate`, `closed_at`, `last_message_at`, `last_response_at`, `tickets`.`created_at`, `tickets`.`updated_at` from `users` inner join `tickets` on `users`.`id` = `tickets`.`user_id` and `tickets`.`id` = 2097 limit 1)","file":"\/home\/ladybirq\/public_html\/support\/code\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/Connection.php","line":713}

**Comment by vijaysebastian** [comment]
We have fixed this issue. The reason for this issue, Old version of faveo had a database field last_message_at, But we removed this in latest version. But that version we have't update in ladybird. However this issue is no more in ladybird, I fixed
