### ISSUE TITLE
Reply Ticket Response

### ISSUE THREAD

**Issue by narendra-baratam** [ladybirdweb/faveo-helpdesk-android-app#57]
Need to add "first_name" attribute to the existing attributes.

**API**: http://faveohelpdesk.co.in/saifu/public/api/v1/helpdesk/reply?

**Actual Response**:
{
  "result": {
    "ticket_id": "38",
    "poster": "support",
    "body": "hello saifu",
    "user_id": 1,
    "updated_at": "2016-10-10 12:38:25",
    "created_at": "2016-10-10 12:38:25",
    "id": 188
  }
}

**Required Response**:
{
  "result": {
    "first_name": "test"
    "ticket_id": "38",
    "poster": "support",
    "body": "hello saifu",
    "user_id": 1,
    "updated_at": "2016-10-10 12:38:25",
    "created_at": "2016-10-10 12:38:25",
    "id": 188
  }
}

**Comment by bhanu2217** [comment]
Is this issue resolved?
