### ISSUE TITLE
How can I set COPMANY'S URL programmatically?

### ISSUE THREAD

**Issue by lovebdsobuj** [ladybirdweb/faveo-helpdesk-android-app#59]

**Comment by bhanu2217** [comment]
Company URL is the URL where Faveo is installed.
This URL will get saved in the app until logged out.

**Comment by narendra-baratam** [comment]
why you want to do that first! You can do by setting in the loginActivity -->setUpViews()-->editTextCompanyURL.setText("http://exampleURL")

**Comment by lovebdsobuj** [comment]
I want to skip COMPANY'S URL setup page and want to show Login page on
first app start for Individual usage.

**Comment by narendra-baratam** [comment]
you can do that but, do you have any URL ??? then..

**Comment by lovebdsobuj** [comment]
Currently I don't have installed Faveo on my server.
We can use this URL just for demo/quick start purpose as `COMPANY'S
URL` `http://www.faveohelpdesk.com/demo/helpdesk/`

**Comment by narendra-baratam** [comment]
URL: http://www.faveohelpdesk.com/demo/helpdesk/
Username: demo@admin.com
Password: demopass
