### ISSUE TITLE
Create New Ticket

### ISSUE THREAD

**Issue by lovebdsobuj** [ladybirdweb/faveo-helpdesk-android-app#60]
After user login faveo-helpdesk-android-app and trying to create new ticket some field need to be hidden.

- Email
- First Name
- Last Name
- Phone Number

Those field should be under user profile setting and when user create new ticket those filed get automatically from user profile info.

**Comment by bhanu2217** [comment]
Faveo Android App is only for agent and not endUsers/clients

**Comment by lovebdsobuj** [comment]
Do you have plan for make app for endUsers/clients?

**Comment by bhanu2217** [comment]
This is an enterprise Helpdesk application, we don't really see huge use of this mobile app for end users, so we don't plan to make one anytime soon
