### ISSUE TITLE
Regarding MESSAGE text fields in Create Ticket page

### ISSUE THREAD

**Issue by rajdeepak662** [ladybirdweb/faveo-helpdesk-android-app#61]
#60 When I entered characters below 5 for both Subject and Message text fields, its showing as "minimum of 5 characters". But when I entered exactly 5 characters for both the text fields, it is displaying as "Something went wrong".
Version 1.7

**Comment by narendra-baratam** [comment]
I will fix this within a two days

**Comment by rajdeepak662** [comment]
Resolved in Version 1.8
