### ISSUE TITLE
Forgot password? link (Version 1.7)

### ISSUE THREAD

**Issue by rajdeepak662** [ladybirdweb/faveo-helpdesk-android-app#65]
In the login page, when I click on "Forgot password?" link and enter the mail ID and click on Reset password button, this "Reset password" button is not working.

**Comment by narendra-baratam** [comment]
@bhanu2217 @vijaysebastian currently we don't have the password reset system in apps, shall I remove the forget password link from app???

**Comment by bhanu2217** [comment]
Can we check if the API is already existing, if API is not existing, till API is build we should remove this option.
If the API is already existing we should implement this option.

**Comment by narendra-baratam** [comment]
Unfortunately, there is no API for 'forgot Password'.

**Comment by bhanu2217** [comment]
Lets remove this button for now, till the API is build

**Comment by narendra-baratam** [comment]
Resolved in Version 1.9
