### ISSUE TITLE
Closed ticket API

### ISSUE THREAD

**Issue by rajdeepak662** [ladybirdweb/faveo-helpdesk-android-app#68]
SQL issue   {
  "error": "SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query (SQL: select distinct max(ticket_thread.updated_at) as updated_at, `user_name`, `first_name`, `last_name`, `email`, `profile_pic`, `ticket_number`, `tickets`.`id`, `title`, `tickets`.`created_at`, `department`.`name` as `department_name`, `ticket_priority`.`priority` as `priotity_name`, `sla_plan`.`name` as `sla_plan_name`, `help_topic`.`topic` as `help_topic_name`, `ticket_status`.`name` as `ticket_status_name` from `users` inner join `tickets` on `users`.`id` = `tickets`.`user_id` and `status` = 3 or `status` = 2 inner join `department` on `department`.`id` = `tickets`.`dept_id` inner join `ticket_priority` on `ticket_priority`.`priority_id` = `tickets`.`priority_id` inner join `sla_plan` on `sla_plan`.`id` = `tickets`.`sla` inner join `help_topic` on `help_topic`.`id` = `tickets`.`help_topic_id` inner join `ticket_status` on `ticket_status`.`id` = `tickets`.`status` inner join `ticket_thread` on `tickets`.`id` = `ticket_thread`.`ticket_id` and `title` is not null group by `tickets`.`id` order by `updated_at` desc limit 10 offset 0)",
  "file": "/home/ladybirq/public_html/support/code/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
  "line": 729
}

**Comment by narendra-baratam** [comment]
@vijaysebastian  can you pls fix this

**Comment by narendra-baratam** [comment]
resolved
