### ISSUE TITLE
Subject name renaming (version 1.7)

### ISSUE THREAD

**Issue by rajdeepak662** [ladybirdweb/faveo-helpdesk-android-app#69]
I changed the subject name and saved it. And when i checked in the inbox it was changed to new name. But again when clicked on Inbox in the Menu bar, its displaying in the old name.

**Comment by narendra-baratam** [comment]
again it because of cache data. @rajdeepak662  Test the latest version.

**Comment by narendra-baratam** [comment]
check now again

**Comment by rajdeepak662** [comment]
Resolved in v1.8
