### ISSUE TITLE
Phase 1 testing

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/faveo-helpdesk-android-app#7]
- demo URL is hard coded
- In the ticket inbox page, unable to figure out which is subject, which is customer name, some place the subject is there, some place it's not there
- Loader image needs to be put every where
- Ticker conversation/detail page show Gravtar
- On the ticket detail page click of Plus button should show you two option to reply to ticket or to add internal to ticket, Check this http://jamboreebliss.com/Karthik/demo/faveomobile/ticketdetail.html
- Can we have a way to differentiate between internal note and reply. Karthik Please help here
- CC not working, Karthik need to provide new CC design
- Ticket detail page ticket subject not showing
- On Ticket details page not showing who(client) opened the ticket
- Client page on client profile open & close tickets list not showing
- Client profile Put E:, P: in front of email & phone number to understand
- Search option for client list
- Search for ticket list
- No option to move the ticket to trash
- Display the 
- On the ticket detail page differentiate between note & reply

**Comment by bhanu2217** [comment]
Have a look at this sheet also https://docs.google.com/spreadsheets/d/1PirfuYSfNXymVW28y2nPNmam9XkZ_QBcCJklE5IoxpU/edit#gid=627241066

**Comment by sumitl920** [comment]
The app again won't work after the token has expired. I still get no value on expiration. I am looking for exactly these characters: Token has expired
All I get here is null

•demo URL is hard coded
Fixed

•In the ticket inbox page, unable to figure out which is subject, which is customer name, some place the subject is there, some place it's not there
Does not come from the backend

•Loader image needs to be put every where
Not clear

•Ticker conversation/detail page show Gravtar
Does not come from the backend.
Have already mentioned this on the "Requirements" sheet in google sheets.

•On the ticket detail page click of Plus button should show you two option to reply to ticket or to add internal to ticket, Check this http://jamboreebliss.com/Karthik/demo/faveomobile/ticketdetail.html 
Fixed

•Can we have a way to differentiate between internal note and reply. Karthik Please help here
Fixed

•CC not working, Karthik need to provide new CC design
Dependency

•Ticket detail page ticket subject not showing
Does not come from the backend for few/all tickets
Have already mentioned this on the "Requirements" sheet in google sheets.

•On Ticket details page not showing who(client) opened the ticket
Have put the client name on the top of the Detail tab

•Client page on client profile open & close tickets list not showing
I always get this response while fetching tickets of a client: {"error":"This user is not an Aget or Admin"}
Have already mentioned this on the "Client list" sheet in google sheets.

•Client profile Put E:, P: in front of email & phone number to understand
Have put phone/email icons before respective texts

•Search option for client list
Search for ticket list
Both searches will take time to implement. Won't be doing this.

•No option to move the ticket to trash

•Display the 
Not clear

•On the ticket detail page differentiate between note & reply
Have put an icon of reply/note before timestamp.
note - the server has to send is_reply as "true" in String for this to work. Default is "true".
called url - helpdesk/ticket-thread and helpdesk/reply

**Comment by bhanu2217** [comment]
@sumitl920 We also need to change App Logo on the mobile, if you let us know the format and size we can send you the app logo

**Comment by bhanu2217** [comment]
@vijaysebastian Please respond to API related issues and help Sumit on this.

**Comment by vijaysebastian** [comment]
- In inbox api response title is the subject and customer names like first_name, last_name is there in response
- From Backend we are passing profile_pic, if you need gravatar url I can pass. Please mention in which api you need gravatar url.
- {"error":"This user is not an Aget or Admin"}, let me check what happened.

**Comment by ssmittal** [comment]
@sumitl920 
1. In mobile app once we open it we get the welcome page we don't want that. Can you please remove it.
2. We are still facing the same issues as  before, we are not able to open the app after few days. As you discussed about the token_expire needs to be call from the back end. Can you please check that as well.

**Comment by bhanu2217** [comment]
@sumitl920 
First time URL, User id & password should be saved in the app. Only system should ask for these details after the logout button is clicked, every time the app starts this information should be loaded from cache.

In case token expired it should be refreshed again with the information that is saved in the app cache, user shouldn't be asked to enter all this information again on token expire

**Comment by bhanu2217** [comment]
When user clicks logout then delete the cache information which is url, user id & password. Till the time logout is not clicked this information should be accessible from app cache and user shouldn't be prompted to enter this information ever on closing, opening or using the app.

**Comment by vijaysebastian** [comment]
{"error":"This user is not an Aget or Admin"}, let me check what happened. for this I have created two api for client's ticket and agent's tickets. Agent's ticket means ticket assign to the agent and user's ticket is ticket created by user.
- For agent tickets api  api/v1/helpdesk/my-tickets-agent. api documentation number 28.
- For user tickets api api/v1/helpdesk/my-tickets-user. api documentation number 29.

Now you will get the avatar url in profile_pic field. Wherever backend giving profile_pic field you will get a link for the avatar

**Comment by bhanu2217** [comment]
We can leave ticket delete/trash option out of phase 1 android app, as this logic will change soon in our API/web app
