### ISSUE TITLE
Trash page(version 1.7)

### ISSUE THREAD

**Issue by rajdeepak662** [ladybirdweb/faveo-helpdesk-android-app#71]
I changed the status of a ticket from Open to Deleted in Inbox page. Update was successful. But the same ticket is still present in the Inbox when i navigated to Inbox through Menu bar.

**Comment by narendra-baratam** [comment]
Because of cache, anyhow I removed the cache code in the latest version. @rajdeepak662 test this again

**Comment by rajdeepak662** [comment]
Resolved in v1.8
