### ISSUE TITLE
Inbox page(Version 1.7)

### ISSUE THREAD

**Issue by rajdeepak662** [ladybirdweb/faveo-helpdesk-android-app#73]
In the Inbox page, when i refresh the page, it is displaying all the tickets created in the sorted way. But later when i click on the "Inbox page in the Menu page, it is displaying the previously created tickets and not the tickets that were created recently.

**Comment by narendra-baratam** [comment]
Because of the locally cached data, I resolved in the latest version.

**Comment by narendra-baratam** [comment]
@rajdeepak662 did you check this ??

**Comment by rajdeepak662** [comment]
Resolved in v1.8
