### ISSUE TITLE
"Reply" field is not working(Version 1.8)

### ISSUE THREAD

**Issue by rajdeepak662** [ladybirdweb/faveo-helpdesk-android-app#83]
In Reply window, after filling the cc and mesage fields when i click on Send button, it is displaying as "Something went wrong"

**Comment by narendra-baratam** [comment]
API: http://faveohelpdesk.co.in/narendra/public/api/v1/helpdesk/reply?api_key=9p41T2XFZ34YRZJUNQAdmM7iV0Rr1CjN&ip=null&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6XC9cL2ZhdmVvaGVscGRlc2suY28uaW5cL25hcmVuZHJhXC9wdWJsaWNcL2FwaVwvdjFcL2F1dGhlbnRpY2F0ZSIsImlhdCI6MTQ4MzYxODgyNCwiZXhwIjoxNDgzNjE5MDY0LCJuYmYiOjE0ODM2MTg4MjQsImp0aSI6Ijc5ODVhM2UwMTE1MGY3YzA4YWM1NjhjMzEyMDFiMjhlIn0.3fQ8P_MnQgk_1O723oFwyfu86eJJo5yIqEIoJTOSot4&ticket_ID=4&cc=&reply_content=hgtdfhgfdh+jhvbhjv+hv

Checked in POSTMAN
Error: 500 internal server error

**Comment by rajdeepak662** [comment]
When I fill the cc and message fields and click on send button, a message is displayed as "Something went wrong". But as i refreshed the Ticket Detail page, the Reply note is created.
