### ISSUE TITLE
Taking "name" of the client which was created earlier(Version 1.8)

### ISSUE THREAD

**Issue by rajdeepak662** [ladybirdweb/faveo-helpdesk-android-app#84]
When I created a new ticket for the same mail ID(already in client list) but with different name, it is taking the same name that was entered while creating the very first ticket for that particular mail ID.

**Comment by kreatorcodes** [comment]
For every email we create one unique account in the application. If user is entering the email which is already registered in the system we create a ticket for already existing user with that email address. This way we avoid the situation of creation of multiple accounts as every user has unique email address.
