### ISSUE TITLE
Username and password Mismatch

### ISSUE THREAD

**Issue by abusomani** [ladybirdweb/faveo-helpdesk-android-app#88]
I am trying to login into faveo app. 
For username : demo_admin / demo_client / demo_agent / demoadmin 
and password : demopass
It is showing invalid credentials.
Plus the reset password button isn't responding!

**Comment by SarfrazS** [comment]
Hi Abusomani,

Please can you tell me which url you are using for Android app with credentials. Don't use above credentials for community android app. These credentials only for Faveo Pro.

**Comment by abusomani** [comment]
URL : http://faveo.jeeja.biz/public
Username and password are those with which I registered on Faveo.

**Comment by SarfrazS** [comment]
Yes, Can you provide us username and password, then i will check it.

**Comment by abusomani** [comment]
Can you provide your email ID? Revealing username and password might raise privacy concerns!

**Comment by SarfrazS** [comment]
mdsarfraz.ansari@ladybirdweb.com

**Comment by narendra-baratam** [comment]
resolved
