### ISSUE TITLE
community version & localhosted

### ISSUE THREAD

**Issue by chazkame** [ladybirdweb/faveo-helpdesk-android-app#96]
Hi,

I have installed in local server the community version of faveo helpdesk. When I tried using the android app, i can't access the url using the ip address of the server.

**Comment by bhanu2217** [comment]
I highly recommend you use the Freelancer plan here https://www.faveohelpdesk.com/pricing/ and this app with freelancer plan https://play.google.com/store/apps/details?id=com.faveo.helpdesk.rn
